### ISSUE TITLE
Error: 'sqlite3.Connection' object has no attribute 'enable_load_extension'

### ISSUE THREAD

**Issue by shanedoolane** [yannforget/pylandsat#14]
Trying to run 
```
from datetime import datetime
from shapely.geometry import Point
from pylandsat import Catalog, Product

catalog = Catalog()

begin = datetime(2010, 1, 1)
end = datetime(2020, 1, 1)
geom = Point(4.34, 50.85)


# Results are returned as a list
scenes = catalog.search(
    begin=begin,
    end=end,
    geom=geom,
    sensors=['LE07', 'LC08']
)

product_id = scenes[0].get("product_id")

print(scenes)
```

but erroring out with sqllite3 problem. Anyone seen this issue? Running on pycharm installation

**Comment by relativityhd** [comment]
You need to install Python with some Feature flags. I deinstalled my python an reinstalled it with PyEnv. Before installing the python version I installed some other libraries which are then automaticly used by PyEnv for the install:

```sh
$ sudo apt update; sudo apt install build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev libsqlite3-mod-spatialite curl \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
$  PYTHON_CONFIGURE_OPTS="--enable-loadable-sqlite-extensions --enable-optimizations" pyenv install 3.11
```

Hope this helps

**Comment by tristannew** [comment]
I have also been having the same issue appear.

I have tried @relativityhd solution without uninstalling python. I already use pyenv so I just set the local version to 3.11 using `pyenv local 3.11`.

I am still not having any luck though, I was wondering if anyone has solved the issue in the same or a different way?

**Comment by relativityhd** [comment]
> I have also been having the same issue appear.
> 
> I have tried @relativityhd solution without uninstalling python. I already use pyenv so I just set the local version to 3.11 using `pyenv local 3.11`.
> 
> I am still not having any luck though, I was wondering if anyone has solved the issue in the same or a different way?

You need to reinstall the python version, so that the PyEnv building script can link the other dependencies to the Python installation. Without that my solution won't work, because the installed Python installation has not been linked to the dependencies.

**Comment by tristannew** [comment]
Thank you for the response! 

I have tried uninstalling, reinstalling and setting the version using 

```
pyenv uninstall 3.11
PYTHON_CONFIGURE_OPTS="--enable-loadable-sqlite-extensions --enable-optimizations" pyenv install 3.11
pyenv local 3.11
```

It still doesn't seem to be working for me. Would you mind sharing the commands that you would expect to work, please? As I think I am misunderstanding something.

**Comment by relativityhd** [comment]
Should be the right commands. What exactly is your error message? What other installations are on your system? `pyenv versions`

**Comment by lachlanjc** [comment]
@relativityhd I'm having the same issue after running the install command Tristan provided:

```bash
lachlanjc@10-18-143-178 superfund % python lib/tasks/landsat.py lib/data/sites.json
/Users/lachlanjc/.pyenv/versions/3.11.11/lib/python3.11/site-packages/rasterio/path.py:15: RasterioDeprecationWarning: rasterio.path will be removed in version 1.4.
  warnings.warn(
Sites:   0%|                                                                                                                          | 0/1840 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/lachlanjc/src/edu/superfund/lib/tasks/landsat.py", line 60, in nearest_scene
    scenes = catalog.search(
             ^^^^^^^^^^^^^^^
  File "/Users/lachlanjc/.pyenv/versions/3.11.11/lib/python3.11/site-packages/pylandsat/catalog.py", line 97, in search
    scenes = self.db.query(
             ^^^^^^^^^^^^^^
  File "/Users/lachlanjc/.pyenv/versions/3.11.11/lib/python3.11/site-packages/pylandsat/database.py", line 67, in query
    conn = self.connect()
           ^^^^^^^^^^^^^^
  File "/Users/lachlanjc/.pyenv/versions/3.11.11/lib/python3.11/site-packages/pylandsat/database.py", line 61, in connect
    conn.enable_load_extension(True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'
```

**Comment by tristannew** [comment]
@lachlanjc Apologies for going quiet on this thread.

I did eventually get the fix that I needed, but unfortunately, I didn't document it very well (and I don't think it is the cleanest fix). If it is useful, though, I ended up editing the code in the local `pylandsat` package that my virtual environment uses. What I can see that I have done is:

1. Change the Python and numpy versions that are used in the `pyproject.toml` to 
    - `python = ">=3.10,<4.0"`
    - `numpy = "^2.1.1"`
1.  In the `database.py` file, update the variable called `WRS_URL` (on line 131) to:
    - `WRS_URL = 'https://s3.us-west-2.amazonaws.com/prd-wret/assets/palladium/production/s3fs-public/atoms/files/WRS2_descending_0.zip'`

As I said, I didn't do the best job of documenting these changes, but this is what I can see that I have done. Hopefully, that is useful!
